[phases.install]
cmds = [
  "npm install",
  "cd server && npm install",
  "cd client && npm install"
]

[phases.build]
cmds = [
  "cd client && npx vite build",
  "cd server && npx prisma generate && npx tsc"
]

[start]
cmd = "cd server && npx prisma migrate deploy && node dist/index.js"
